const errorMessages = {
    200: "Success",
    500: "Internal server error.",
    100: "Header is missing",
    101: "Device type invalid",
    102: "Invalid Api Key",
    103: "A token is required for authentication",
    104: "Invalid Token",
    105: "Request validation error (returning message key with this)",
    106: "Internal server error",
    107: "User not found.",
    108: "User account blocked",
    109: "Social user not found",
    110: "Invalid gender name",
    111: "Invalid login credentials",
    112: "Email already exist",
    113: "Email send fail",
    114: "Email limit exceeded",
    115: "invalid login credentials",
    116: "Code already used",
    117: "Code does not match",
    118: "The code you entered is incorrect. Please try again.",
    119: "Social ID already exists",
    120: "Email linked with social",
    121: "Email linked with normal",
    123: "Email send failed",
    124: "Admin pass code does not match",
    125: "Admin pass code already used",
    126: "Message sending failed",
    127: "OTP limit exceeded",
    128: "OTP did not send",
    129: "OTP did not match",
    130: "Phone OTP did not match",
    131: "Email OTP did not match",
    132: "Step value must be type file",
    133: "Step value must have at least six images",
    134: "File size limit exceeded. Max allowed is 10 MB",
    135: "Invalid file type, allowed extensions: .jpg, .jpeg, .gif, .png, .webp",
    136: "Must upload a single audio file",
    137: "Audio size limit exceeded. Max allowed is 30 MB",
    138: "Invalid audio file, allowed extensions: mp3, wav, aac, flac, ogg, wma, aiff, alac, m4a, amr",
    139: "Invalid ref key",
    140: "Invalid gender ID",
    141: "Now you both users are friends",
    142: "Liked to user",
    143: "Already disliked",
    144: "Already liked",
    145: "Invalid user",
    146: "Invalid notification ID",
    147: "DB error",
    148: "Chat restricted",
    149: "Invalid parent value code",
    150: "Invalid relative ref key",
    151: "Invalid individual ref key",
    152: "Meta value already exists",
    153: "Meta unable to delete, it's already used",
    154: "Already reported user",
    155: "Invalid question ID",
    156: "Question already exists",
    157: "Question unable to delete, it's used with a user, remove it first",
    158: "Invalid answer ID",
    159: "Answer unable to delete, it's already used with a user",
    160: "User profile already reviewed",
    161: "Your date is already fixed with this user",
    162: "Now you are not friends, unable to create/update date",
    163: "Date must be greater than or equal to the current date",
    164: "Invalid dating ID",
  };
  
  export const getErrorMessage = (code) => {
    return errorMessages[code] || "Unknown error occurred.";
  };
  